[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gsb-dna"
version = "1.0.1"
description = "Genetic Systems Builder algorithm for low-cost, high-throughput DNA assembly"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [
  { name = "Howard Salis", email = "howard.salis@ucr.edu" }
]
keywords = ["synthetic biology", "dna assembly", "oligopool", "PCR", "golden gate"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
  "biopython",
  "joblib",
  "networkx",
  "numba",
  "numpy",
  "openpyxl",
  "pandas",
  "requests",
  "rocksdict",
  "scipy",
  "setuptools",
  "ViennaRNA"
]

[project.scripts]
gsb = "GeneticSystemsCalculator_Build:main"

[project.urls]
Homepage = "https://github.com/hsalis/GeneticSystemsBuilder"
Source = "https://github.com/hsalis/GeneticSystemsBuilder"
Preprint = "https://doi.org/10.64898/2026.06.08.729977"

[tool.setuptools]
py-modules = [
  "GeneticSystemsCalculator_Build",
  "GeneticSystemsCalculator_Build_Helpers",
  "GeneticSystemsCalculator_ModelFunctions",
  "PyVRNA",
  "nrpcalc"
]

[tool.setuptools.packages.find]
include = [
  "NRP_Calculator",
  "NRP_Calculator.*",
  "data"
]

[tool.setuptools.package-data]
"NRP_Calculator.base" = ["*.par"]
"data" = ["*.csv", "*.csv.zip", "*.xlsx"]
